apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dbis-sport-master
  name: dbis-sport-master
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dbis-sport-master
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dbis-sport-master
    spec:
      containers:
      - image: dbissportmaster.azurecr.io/dbis-sport-master:latest
        name: dbis-sport-master
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 4200
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: dbis-sport-master
  labels:
    run: dbis-sport-master
spec:
  ports:
  - port: 4200
    protocol: TCP
  selector:
    app: dbis-sport-master
  type: LoadBalancer