apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dbis-sport-master
  name: dbis-sport-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbis-sport-master
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dbis-sport-master
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - image: dbissportmaster.azurecr.io/dbis-sport-master:latest
        name: dbis-sport-master
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 4200
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: dbis-sport-master
  labels:
    run: dbis-sport-master
spec:
  ports:
  - port: 4200
  selector:
    app: dbis-sport-master
  type: LoadBalancer
